"""Persistence and bounded query ports for paper research data."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from paper_trading.domain.entities import (
    BotDecisionRecord,
    BotDefinitionRecord,
    ExperimentRecord,
    ExperimentStatus,
    PaperSessionRecord,
    PaperTradeRecord,
    PerformanceReport,
    PortfolioSnapshotRecord,
    PositionRecord,
    SessionBotRecord,
    SessionStatus,
)


class ResearchWritePort(Protocol):
    async def add_session(self, value: PaperSessionRecord) -> None: ...
    async def add_bot_definition(self, value: BotDefinitionRecord) -> None: ...
    async def add_session_bot(self, value: SessionBotRecord) -> None: ...
    async def add_snapshot(self, value: PortfolioSnapshotRecord) -> None: ...
    async def add_position(self, value: PositionRecord) -> None: ...
    async def add_trade(self, value: PaperTradeRecord) -> None: ...
    async def add_decision(self, value: BotDecisionRecord) -> None: ...
    async def add_experiment(self, value: ExperimentRecord) -> None: ...
    async def set_session_status(
        self, session_id: UUID, status: SessionStatus, ended_at: datetime | None = None
    ) -> None: ...
    async def set_experiment_status(
        self, experiment_id: UUID, status: ExperimentStatus, ended_at: datetime | None = None
    ) -> None: ...


class ResearchQueryPort(Protocol):
    async def active_sessions(self, limit: int = 50) -> tuple[PaperSessionRecord, ...]: ...
    async def session(self, session_id: UUID) -> PaperSessionRecord | None: ...
    async def session_bots(self, session_id: UUID) -> tuple[SessionBotRecord, ...]: ...
    async def bot_definitions(
        self, bot_ids: tuple[UUID, ...]
    ) -> tuple[BotDefinitionRecord, ...]: ...
    async def current_portfolio(self, session_bot_id: UUID) -> PortfolioSnapshotRecord | None: ...
    async def portfolio_history(
        self, session_bot_id: UUID, start: datetime | None = None, limit: int = 2_000
    ) -> tuple[PortfolioSnapshotRecord, ...]: ...
    async def open_positions(self, session_bot_id: UUID) -> tuple[PositionRecord, ...]: ...
    async def recent_trades(
        self, session_id: UUID | None = None, limit: int = 200
    ) -> tuple[PaperTradeRecord, ...]: ...
    async def decisions(
        self, session_bot_id: UUID, limit: int = 500
    ) -> tuple[BotDecisionRecord, ...]: ...
    async def experiments(self, limit: int = 100) -> tuple[ExperimentRecord, ...]: ...
    async def experiment(self, experiment_id: UUID) -> ExperimentRecord | None: ...
    async def performance(self, session_bot_id: UUID) -> PerformanceReport | None: ...
